version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 445567116039.dkr.ecr.us-east-1.amazonaws.com
      - echo "📦 Setting the image repository URI..."
      - REPO_URI=445567116039.dkr.ecr.us-east-1.amazonaws.com/arjun-ecs-repo
      - IMAGE_TAG=latest
  build:
    commands:
      - echo "🔨 Building the Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "🚀 Pushing the Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
artifacts:
  files: '**/*'
