version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t arjun-ecs-repo .
      - docker tag arjun-ecs-repo:latest 445567116039.dkr.ecr.us-east-1.amazonaws.com/arjun-ecs-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 445567116039.dkr.ecr.us-east-1.amazonaws.com/arjun-ecs-repo:latest
      - echo Writing imagedefinitions.json...
      - echo '[{"name":"arjun-container","imageUri":"445567116039.dkr.ecr.us-east-1.amazonaws.com/arjun-ecs-repo:latest"}]' > imagedefinitions.json

artifacts:
  base-directory: ./
  files:
    - imagedefinitions.json
